import React, { ReactNode } from "react";
import Navbar from "../Navbar";
import styles from "./styles.module.scss";
import Head from "next/head";

interface Children {
  children: ReactNode;
}

const Layout = ({ children }: Children) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Rainmakr</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>

      <Navbar />
      <div style={{ marginTop: "40px" }}>{children}</div>
    </div>
  );
};

export default Layout;
